---
-
  hosts: windows
  gather_facts: false
  strategy: free
  vars:
    aoag_prechecks: ""
    aoag_postchecks: ""
    aoag_postfailoverchecks: ""
    aoag_secondarychecks: ""



  tasks:

        - name: AOAG Pre-Reboot Checks
          include_tasks: aoag_checks.yaml
          # register: aoag_postchecks
          tags:
                  AOAGPreChecks

        - name: Parse AOAG Pre-check
          set_fact:
                  aoag_prechecks: "{{ aoag_config }}"


        - name: Display Pre Checks
          debug:
            var: aoag_prechecks.Role


        - name: Check until the primary becomes secondary
          include_tasks: wait_for_ag_secondary.yaml
          vars:
                max_retries: 4
                delay_between_retries: 300
                ag_attempts: 1
          when: 
                - aoag_prechecks.AlwaysOn == 1
                - aoag_prechecks.Role == "PRIMARY"
                - aoag_prechecks.State == 1

        - name: Reset ag_attempts 
          set_fact:
            ag_attempts: 1

        - name: AOAG Post Secondary Transition Checks
          include_tasks: aoag_checks.yaml
          # register: aoag_postchecks
          tags:
                  AOAGPreChecks

        - name: Parse AOAG Post secondary Transition Checks
          set_fact:
                  aoag_prechecks: "{{ aoag_config }}"


        - name: Display Post Secondary  Checks
          debug:
            var: aoag_prechecks.Role


        #- name: Reboot Secondary
         # win_reboot:
          #        reboot_timeout: 900
          #when:
           #     - aoag_prechecks.Role == "SECONDARY" 
            #    - aoag_prechecks.State == 1


        #- name: Pause for the services to come online
         # pause:
          #  minutes: 1


        - name: Get the Service status
          win_service:
            name: 'ClusSvc'
          register: service_status

        - name: Display raw Info
          debug:
            var: service_status


        - name: Display service state
          debug:
            var: service_status.state
         

        #- name: Wait for the service to be running
         # win_wait_for:
          #  timeout: 90
           # #path: "{{ ansible_host }}"
          #until: service_status.state == "running"
          #retries: 2
          #delay: 30
          ##when: service_status.services is defined

        #- name: AOAG post Reboot Checks
         # include_tasks: aoag_checks.yaml
          ## register: aoag_postchecks
          #tags:
           #       AOAGPostChecks

        #- name: Parse AOAG Post Checks
         # set_fact:
          #        aoag_postchecks: "{{ aoag_config }}"

                 
        #- name: Display Post Checks
         # debug:
          #  var: aoag_postchecks.Role

        - name: Failover AG if Secondary is sync
          win_shell: |
                  $query4 = "ALTER AVAILABILITY GROUP [{{ aoag_prechecks.AGName }}] FAILOVER;"
                  $failoverResult = Invoke-Sqlcmd -Query $query4
                  #$failoverResult | ConvertTo-Json
          register: failoverstate
          when: 
                - aoag_prechecks.State == 1
                - aoag_prechecks.Role == "SECONDARY"

        
        - name: Display Raw failover checks
          debug:
            var: failoverstate


        #- name: Parse Failover status
        #  set_fact:
        #          failover_checks: "{{ failoverstate.stdout | from_json }}"

        - name: Display failover checks
          debug:
            var: failoverstate.changed


        - name: AOAG post Failover Checks
          include_tasks: aoag_checks.yaml
          # register: aoag_postchecks
          tags:
                  AOAGPostChecks

        - name: Parse AOAG Post Checks
          set_fact:
                  aoag_postfailoverchecks: "{{ aoag_config }}"

                 
        - name: Display Post Checks
          debug:
            var: aoag_postfailoverchecks.Role


...
